### ISSUE TITLE
Can you add Qtranslate support?

### ISSUE THREAD

**Issue by Tusko** [mrwweb/post-type-archive-descriptions#1]

**Comment by mrwweb** [comment]
I'll try to do some research and testing, but can you provide any more information on the way you'd expect translation to work and (if you know) how to add qTranslate support?

**Comment by Tusko** [comment]
@mrwweb Added!
http://awesomescreenshot.com/0cc5dv4b51

Just for testing
http://tt.dev3.belugalab.com/cpt/

**Comment by Tusko** [comment]
you inspired me for new plugin
https://github.com/Tusko/ACF-CPT-Options-Pages

now without documentation, but I'll create it soon

**Comment by mrwweb** [comment]
Addressed by #2
