### ISSUE TITLE
Can't add a description to the default post type via ptad_post_types filter

### ISSUE THREAD

**Issue by certainlyakey** [mrwweb/post-type-archive-descriptions#5]
Hi!
Thanks for a great(ly designed) plugin.
I've got one problem though. 
I've tried to add an archive description to the default blog post type. I used this code in `functions.php`:

````php
function add_descriptions_to_post_types($posttypes) {
      $posttypes['post'] = 'post';
      return $posttypes;
}
add_filter( 'ptad_post_types', 'add_descriptions_to_post_types' );
````
However, no description link appeared in the admin menu in the Posts menu section. I also tried to assign `get_post_types()` instead of adding just one array member. Other post types have successfully got their description pages, but not this one. I also tried other built-in post types, namely pages, and it worked with them but not with posts.

Is there a way to make it so that posts get a description too?

Thanks a lot!

**Comment by mrwweb** [comment]
Thanks for the report.

I think I see what's going on. I didn't really build this to work with posts, but this seems like a reasonable enough request :) I'll try to get an update out with a fix, but can you try this in the mean time (untested):

Replace [lines 123 and 124 in post-type-archive-descriptions.php](https://github.com/mrwweb/post-type-archive-descriptions/blob/master/post-type-archive-descriptions.php#L123) with this:

```php
			$parent_slug = 'edit.php?post_type=' . $post_type;
			if( 'post' === $post_type ) {
				$parent_slug = 'edit.php';
			}
			add_submenu_page(
				$parent_slug, // $parent_slug
```

Let me know if that works.

**Comment by mrwweb** [comment]
Update: Having done the above change, it fixes the menu item but there seem to be some further issues still. I'm working on a fix but it might take a while.

**Comment by certainlyakey** [comment]
Thanks for looking into this! I've done the same change, but for some reason nothing changed, the menu item didn't reappear as well. Here's how the whole `if` block looks right now, lines 121-136: 

````php
if( post_type_exists( $post_type ) ) {

	$parent_slug = 'edit.php?post_type=' . $post_type;
	if( 'post' === $post_type ) {
		$parent_slug = 'edit.php';
	}
	add_submenu_page(
		$parent_slug, // $parent_slug
		ptad_settings_page_title( $post_type, 'name' ), // $page_title
		ptad_settings_menu_label( $post_type, 'name' ), // $menu_label
		'edit_posts', // $capability
		$post_type . '-description', // $menu_slug
		'ptad_settings_page' // $function
	);

} // end if
````

**Comment by mrwweb** [comment]
@certainlyakey After years of experience with this issue, I'm going to close this issue. (But the request is not dead yet!)

Posts are inherently different because they are displayed on a Page (the `page_for_posts`) option and not in a Post Type Archive. Therefore, I prefer [allowing editors to edit the blog Page](https://wordpress.org/support/topic/not-working-on-posts-9/) as a means of editing the top of the blog rather than using a post type archive description.

I've opened #22 and any feedback you have on that approach would be great!
