### ISSUE TITLE
Add WPML Support

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/post-type-archive-descriptions#6]
https://wordpress.org/support/topic/wpml-support-74/

**Comment by abombelli** [comment]
@mrwweb Quite some time ;-) Any news on this?

**Comment by mrwweb** [comment]
Thanks for the bump @abombelli! I just merged support. I've only tested in Polylang, but Polylang uses the WPML format, so I expect it to work in WPML too.

**Comment by abombelli** [comment]
@mrwweb Thanks for the feedback. Just installed the updated and tested it. Unfortunately the translated string is not saved. So we get on all languages the last saved text.

**Comment by mrwweb** [comment]
Could you post a few screenshots showing your issue in more detail? I'm not
quite sure I understand what's going on. Thanks for testing so quickly!

**Comment by mrwweb** [comment]
@abombelli I just tested the plugin with WPML and was able to translate the Archive Description. Note that you have to use the String Translations plugin to do the translation (which is available in WPML > String Translation) once installed. Another thing that caught me up briefly was that I needed to enable translations for the post type and add a post before I could view the archive.

I'm using the latest version of WordPress, WPML, and String Translations with the Twenty Twenty One theme.

I am going to close this issue since I see it working. If you're still having issues, please open up a new ticket specifically describing your issue, and including screenshots, steps to reproduce, and the versions of everything you're using.

Thanks again for testing this so quickly, and I hope you're able to get things working soon!

**Comment by abombelli** [comment]
@mrwweb Thanks for the Feedback. Yes, it works over string translation, but not when accessing it over the description field an changing the language. This would normally be expected behaviour, when editing multilingual fields. Any chance to get this working there? A "normal" user should not edit content in string translation.
Thanks!

**Comment by mrwweb** [comment]
Gotcha. I have no idea how hard that would be or what's involved. Because WordPress doesn't have native support for Custom Post Type descriptions, the implementation has to rely on an option rather than a post, so the translation mechanism is the same. I'll open a new issue to look into improving the implementation, but for now, I think I will leave this issue closed as it does work in a basic way.
