### ISSUE TITLE
Can't create descriptions page for nested post types

### ISSUE THREAD

**Issue by eyesofjeremy** [mrwweb/post-type-archive-descriptions#9]
Hi! Thanks for a great plugin, this seems like the right approach to quickly add something which feels almost like it should be core.

I ran into a hitch on a site for a client. I've created a Garden Guide, and the top level page allows editors to add plants, one post type. Within that admin menu, they also can add fauna and diseases, two other post types. This plugin assumes that each post type has its own top-level spot in the admin menu, but post types can be [registered with a custom menu location](https://codex.wordpress.org/Function_Reference/register_post_type#Arguments).

In my case, enabling the plugin led to three different settings pages which all pulled in the plants post type, since the parent menu item was `/edit.php?post_type=plant`.

I've created a fix which works in my case, but it may not be a complete solution. I'll create a pull request, and hopefully it helps out! If you see any issues, let me know.

Thanks!
Jeremy

**Comment by mrwweb** [comment]
@eyesofjeremy thanks for the bug report. I've never tested this situation but what you're describing makes complete sense. I'll look forward to seeing your PR! Thanks in advance.

**Comment by eyesofjeremy** [comment]
Okay, submitted. (Was writing PR and decided I should describe the issue separately) Hope it's useful!
